### ISSUE TITLE
please tell how to generate `token_v2`

### ISSUE THREAD

**Issue by 4geru** [tpgunther/notion_rb#12]
Thank you for releasing a nice gem.
I am so excited that I also want to participate in the development :)

By the way, the method of issuing `token_v2` is not described, so you cannot try it on local environment.
If you like, I would like you to describe the acquisition method in README.md, but how about it?

**Comment by kevinjalbert** [comment]
@4geru you can look at the following for how I've gotten my `token_v2` for my own project.

https://github.com/kevinjalbert/notion-toolbox/tree/master/alfred#finding-your-notion-token

**Comment by 4geru** [comment]
Thanks a lot. I can use this gem and join develop :)
